var data = [
    {
        "number":1,
        "name":"张三",
        "age":18,
        "sex":"男",
    },
    {
        "number":2,
        "name":"零二",
        "age":18,
        "sex":"男",
    },
    {
        "number":3,
        "name":"零三",
        "age":18,
        "sex":"男",
    },
    {
        "number":4,
        "name":"零四",
        "age":18,
        "sex":"男",
    },
    {
        "number":5,
        "name":"零五",
        "age":18,
        "sex":"男",
    },
    {
        "number":6,
        "name":"零六",
        "age":18,
        "sex":"男",
    },
    {
        "number":7,
        "name":"零七",
        "age":18,
        "sex":"男",
    },
    {
        "number":8,
        "name":"零八",
        "age":18,
        "sex":"男",
    },
    {
        "number":9,
        "name":"零九",
        "age":18,
        "sex":"男",
    },
    {
        "number":10,
        "name":"十",
        "age":10,
        "sex":"女",
    },
];